# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui_file\jztzsz.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(400, 461)
        self.verticalLayout = QtWidgets.QVBoxLayout(Form)
        self.verticalLayout.setObjectName("verticalLayout")
        self.verticalLayout_24 = QtWidgets.QVBoxLayout()
        self.verticalLayout_24.setObjectName("verticalLayout_24")
        self.groupBox_11 = QtWidgets.QGroupBox(Form)
        self.groupBox_11.setObjectName("groupBox_11")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.groupBox_11)
        self.verticalLayout_4.setContentsMargins(0, 10, 0, 0)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.listWidget = QtWidgets.QListWidget(self.groupBox_11)
        self.listWidget.setObjectName("listWidget")
        item = QtWidgets.QListWidgetItem()
        self.listWidget.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listWidget.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listWidget.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listWidget.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listWidget.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listWidget.addItem(item)
        self.verticalLayout_4.addWidget(self.listWidget)
        self.verticalLayout_24.addWidget(self.groupBox_11)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.pushButton_addmer = QtWidgets.QPushButton(Form)
        self.pushButton_addmer.setObjectName("pushButton_addmer")
        self.horizontalLayout_4.addWidget(self.pushButton_addmer)
        self.pushButton_2 = QtWidgets.QPushButton(Form)
        self.pushButton_2.setObjectName("pushButton_2")
        self.horizontalLayout_4.addWidget(self.pushButton_2)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem)
        self.verticalLayout_24.addLayout(self.horizontalLayout_4)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_24.addItem(spacerItem1)
        self.verticalLayout.addLayout(self.verticalLayout_24)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.groupBox_11.setTitle(_translate("Form", "Mererials"))
        __sortingEnabled = self.listWidget.isSortingEnabled()
        self.listWidget.setSortingEnabled(False)
        item = self.listWidget.item(0)
        item.setText(_translate("Form", "Fluid"))
        item = self.listWidget.item(1)
        item.setText(_translate("Form", "    water-vapor"))
        item = self.listWidget.item(2)
        item.setText(_translate("Form", "    water-liquid"))
        item = self.listWidget.item(3)
        item.setText(_translate("Form", "    air"))
        item = self.listWidget.item(4)
        item.setText(_translate("Form", "Solid"))
        item = self.listWidget.item(5)
        item.setText(_translate("Form", "    aluminum"))
        self.listWidget.setSortingEnabled(__sortingEnabled)
        self.pushButton_addmer.setText(_translate("Form", "Create/Edit..."))
        self.pushButton_2.setText(_translate("Form", "Delete"))
