# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1200, 600)
        MainWindow.setDockNestingEnabled(False)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.action_newproj = QtWidgets.QAction(MainWindow)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/appres.img/NewFolderHS.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.action_newproj.setIcon(icon)
        self.action_newproj.setObjectName("action_newproj")
        self.action_openproj = QtWidgets.QAction(MainWindow)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/appres.img/openHS.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.action_openproj.setIcon(icon1)
        self.action_openproj.setObjectName("action_openproj")
        self.action_closeproj = QtWidgets.QAction(MainWindow)
        self.action_closeproj.setObjectName("action_closeproj")
        self.action_exit = QtWidgets.QAction(MainWindow)
        self.action_exit.setObjectName("action_exit")
        self.action_config = QtWidgets.QAction(MainWindow)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/appres.img/config.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.action_config.setIcon(icon2)
        self.action_config.setObjectName("action_config")
        self.action_readme = QtWidgets.QAction(MainWindow)
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(":/appres.img/HomeHS.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.action_readme.setIcon(icon3)
        self.action_readme.setObjectName("action_readme")
        self.action_about = QtWidgets.QAction(MainWindow)
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(":/appres.img/Help.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.action_about.setIcon(icon4)
        self.action_about.setObjectName("action_about")
        self.action_historyproj = QtWidgets.QAction(MainWindow)
        self.action_historyproj.setObjectName("action_historyproj")

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.action_newproj.setText(_translate("MainWindow", "新建工程"))
        self.action_openproj.setText(_translate("MainWindow", "打开工程"))
        self.action_closeproj.setText(_translate("MainWindow", "关闭工程"))
        self.action_exit.setText(_translate("MainWindow", "退出"))
        self.action_config.setText(_translate("MainWindow", "配置"))
        self.action_readme.setText(_translate("MainWindow", "使用手册"))
        self.action_about.setText(_translate("MainWindow", "关于"))
        self.action_historyproj.setText(_translate("MainWindow", "历史工程"))

