# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'modellist.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(1199, 734)
        self.verticalLayout = QtWidgets.QVBoxLayout(Form)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.radioButton_alldata = QtWidgets.QRadioButton(Form)
        self.radioButton_alldata.setChecked(True)
        self.radioButton_alldata.setObjectName("radioButton_alldata")
        self.horizontalLayout.addWidget(self.radioButton_alldata)
        self.radioButton_page = QtWidgets.QRadioButton(Form)
        self.radioButton_page.setObjectName("radioButton_page")
        self.horizontalLayout.addWidget(self.radioButton_page)
        spacerItem = QtWidgets.QSpacerItem(35, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.label_t1 = QtWidgets.QLabel(Form)
        self.label_t1.setObjectName("label_t1")
        self.horizontalLayout.addWidget(self.label_t1)
        self.lineEdit_per = QtWidgets.QSpinBox(Form)
        self.lineEdit_per.setMinimumSize(QtCore.QSize(60, 0))
        self.lineEdit_per.setMinimum(1)
        self.lineEdit_per.setMaximum(999)
        self.lineEdit_per.setProperty("value", 18)
        self.lineEdit_per.setObjectName("lineEdit_per")
        self.horizontalLayout.addWidget(self.lineEdit_per)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem1)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.tableView_modelData = QtWidgets.QTableView(Form)
        self.tableView_modelData.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.tableView_modelData.setObjectName("tableView_modelData")
        self.verticalLayout.addWidget(self.tableView_modelData)
        self.widget_2 = QtWidgets.QWidget(Form)
        self.widget_2.setObjectName("widget_2")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.widget_2)
        self.horizontalLayout_2.setContentsMargins(-1, -1, -1, 2)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem2)
        self.pushButton_prepage = QtWidgets.QPushButton(self.widget_2)
        self.pushButton_prepage.setObjectName("pushButton_prepage")
        self.horizontalLayout_2.addWidget(self.pushButton_prepage)
        self.pushButton_nextpage = QtWidgets.QPushButton(self.widget_2)
        self.pushButton_nextpage.setObjectName("pushButton_nextpage")
        self.horizontalLayout_2.addWidget(self.pushButton_nextpage)
        self.label_t2 = QtWidgets.QLabel(self.widget_2)
        self.label_t2.setObjectName("label_t2")
        self.horizontalLayout_2.addWidget(self.label_t2)
        self.label_page = QtWidgets.QLabel(self.widget_2)
        self.label_page.setObjectName("label_page")
        self.horizontalLayout_2.addWidget(self.label_page)
        self.verticalLayout.addWidget(self.widget_2)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.radioButton_alldata.setText(_translate("Form", "所有数据"))
        self.radioButton_page.setText(_translate("Form", "分页查看"))
        self.label_t1.setText(_translate("Form", "每页的数据量："))
        self.pushButton_prepage.setText(_translate("Form", "上一页"))
        self.pushButton_nextpage.setText(_translate("Form", "下一页"))
        self.label_t2.setText(_translate("Form", "当前页："))
        self.label_page.setText(_translate("Form", "0/0"))

