# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'navigate.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(389, 653)
        self.verticalLayout = QtWidgets.QVBoxLayout(Form)
        self.verticalLayout.setObjectName("verticalLayout")
        self.treeWidget_nav = QtWidgets.QTreeWidget(Form)
        self.treeWidget_nav.setSelectionMode(QtWidgets.QAbstractItemView.ContiguousSelection)
        self.treeWidget_nav.setObjectName("treeWidget_nav")
        self.treeWidget_nav.headerItem().setText(0, "1")
        self.verticalLayout.addWidget(self.treeWidget_nav)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
